In [ ]:
import pandas as pd

In [ ]:
df=pd.read_csv('/content/Salary (2).csv')

In [ ]:
df.head()

   rank discipline   phd  service   sex  salary
0  Prof          B  56.0       49  Male  186960
1  Prof          A  12.0        6  Male   93000
2  Prof          A  23.0       20  Male  110515
3  Prof          A  40.0       31  Male  131205
4  Prof          B  20.0       18  Male  104800

In [ ]:
df.tail()

    rank discipline   phd  service     sex  salary
75  Prof          B   NaN       17    Male  124312
76  Prof          B  17.0       17  Female  124312
77  Prof          A  28.0       14  Female  109954
78  Prof          A  23.0       15  Female  109646
79  Prof        NaN  23.0       15    Male  109646

In [7]:
df.describe()

             phd    service         salary
count  79.000000  80.000000      80.000000
mean   19.746835  15.075000  108247.662500
std    12.423580  11.987097   27992.954448
min     1.000000   0.000000   57800.000000
25%    10.500000   5.750000   89837.500000
50%    19.000000  15.000000  104900.000000
75%    27.500000  20.250000  126458.250000
max    56.000000  51.000000  186960.000000

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 80 entries, 0 to 79
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   rank        80 non-null     object
 1   discipline  79 non-null     object
 2   phd         79 non-null     float64
 3   service     80 non-null     int64
 4   sex         80 non-null     object
 5   salary      80 non-null     int64
dtypes: float64(1), int64(2), object(3)
memory usage: 3.9+ KB

In [10]:
df.size

480

In [11]:
df.shape

(80, 6)

In [13]:
df['rank']

0     Prof
1     Prof
2     Prof
3     Prof
4     Prof
      ...
75    Prof
76    Prof
77    Prof
78    Prof
79    Prof
Name: rank, Length: 80, dtype: object

In [15]:
df['rank'].dtype

dtype('O')

In [17]:
df.dtypes

rank           object
discipline     object
phd           float64
service         int64
sex            object
salary          int64
dtype: object

In [18]:
df.columns

Index(['rank', 'discipline', 'phd', 'service', 'sex', 'salary'], dtype='object')